#include <string>
#include <bitset>
#include <iostream>

#include"SDES.h"
#include"sdesData.h"

using namespace std;
int main() {
    SDES s;
    sdesData* d = s.encrypt("As origens do DES remontam ao início da década de 1970. Em 1972, após concluir um estudo sobre as necessidades de segurança de informação do governo norte-americano, o então NBS (National Bureau of Standards), atualmente conhecido como NIST (National Institute of Standards and Technology), na época o órgão de padrões do governo norte-americano) identificou a necessidade de um padrão governamental para criptografia de informações não confidenciais, porém sensíveis. Em conseqüência, em 15 de Maio de 1973, após uma consulta à NSA, o NBS solicitou proposta para um algoritmo de criptografia que atendesse a critérios rigorosos de projeto. Entretanto, nenhuma das propostas recebidas se mostrou viável. Uma segunda solicitação foi aberta em 27 de Agosto de 1974. Desta vez, a IBM submeteu uma proposta candidata que foi considerada aceitável: um algoritmo de criptografia desenvolvido no período de 1973-1974 baseado num algoritmo mais antigo, o algoritmo Lúcifer de Horst Feistel. A equipe da IBM envolvida no projeto do algoritmo incluía Feistel, Walter Tuchman, Don Coppersmith, Alan Konheim, Carl Meyer, Mike Matyas, Roy Adler, Edna Grossman, Bill Notz, Lynn Smith and Bryant Tuckerman. Preocupações sobre a segurança e a operação relativamente lenta do DES motivou pesquisadores a propor uma variedade de alternativas para a cifragem em bloco, que começaram a aparecer no final dos anos 1980 e início dos anos 1990. Alguns exemplos podem ser citados, como: RC5, Blowfish, NewDES, SAFER, CAST5 and FEAL. A maioria deles mantêm o tamanho de bloco de 64 bits do DES, e portanto funcionam como substituição ao DES se necessário, embora usem tipicamente uma chave de 64 ou 128 bits. Na URSS o algoritmo GOST 28147-89 foi introduzido, com um bloco de 64 bits e chave de 256 bits, que mais tarde foi utilizada na Rússia. Até mesmo o próprio DES pode ser adaptado para ser usado de modo mais seguro.Muitos ex - usuários de DES agora utilizam o 3DES(também conhecido como TDES) que foi descrito e analisado por um dos patenteadores do DES; este algoritmo envolve aplicar o DES três vezes com duas(2TDES) ou três(3TDES) chaves diferentes.TDES é considerada adequadamente segura, embora seja bastante lenta.Uma alternativa menos custosa computacionalmente falando é a DES - X, que aumenta o tamanho da chave fazendo um XOR antes e depois do DES.GDES é uma variante do DES proposta de forma a aumentar a velocidade da criptografia, mas mostrou - se suscetível à criptoanálise diferencial.Em 2001, após uma competição internacional, NIST selecionou um novo algoritmo, o AES(Advanced Encryption Standard), como substituto ao DES.O algoritmo que foi selecionado como o AES foi enviado por seus criadores sob o nome Rijndael.Outros finalistas na competição do NIST incluem RC6, Serpent, MARS e Twofish.");
    cout << s.decrypt(d);
}
